{
 "title": "triarb",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "currency",
    "query": "select distinct(currency) from deal_reports where timestamp >=$__timeFrom() and timestamp <$__timeTo()"
   },
   { "name": "server" }
  ]
 },
 "panels": [
  {
   "title": "Total gross profit $currency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT sum(gross_profit) from deal_reports where timestamp >=$__timeFrom() and timestamp <$__timeTo() "
    }
   ]
  },
  {
   "title": "Remainings of  $currency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select coalesce(sum(target_amount_delta),0) from remainings r \nwhere target_currency = '$currency'  \nand timestamp >=$__timeFrom() and timestamp <$__timeTo() \n"
    }
   ]
  },
  {
   "title": "Deals",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as \"time\",exchange, instance, server, deal_uuid,deal_data->'triangle' as \"triangle\", currency,status, gross_profit, start_amount, result_amount,\ndeal_data->'leg1-filled' as \"leg1-filled\", deal_data->'leg2-filled' as \"leg2-filled\", deal_data->'leg3-filled' as \"leg3-filled\",\ndeal_data->'leg1-order-updates' as \"l1-updates\", deal_data->'leg2-order-updates' as \"l2-updates\", deal_data->'leg3-order-updates' as \"l3-updates\" \n\nfrom deal_reports where timestamp >=$__timeFrom() and timestamp <$__timeTo() "
    }
   ]
  }
 ]
}