{
 "title": "trideal",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   { "name": "deal_uuid" }
  ]
 },
 "panels": [
  {
   "title": "Total gross profit $currency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT sum(gross_profit) from deal_reports where deal_uuid = '$deal_uuid'"
    }
   ]
  },
  {
   "title": "Deals",
   "type": "table",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "\nSELECT timestamp as \"time\",exchange, server, dr.deal_uuid,deal_data->'triangle' as \"triangle\", status, gross_profit, start_amount, result_amount,\ndeal_data->'leg1-filled' as \"leg1-filled\", deal_data->'leg2-filled' as \"leg2-filled\", deal_data->'leg3-filled' as \"leg3-filled\"\n\nfrom deal_reports dr\nwhere \n\ndeal_uuid = '$deal_uuid'\n\norder by dr.timestamp desc\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Recovery commands",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "select \r\n (SELECT\r\n  format(' curl -i -X PUT -H \"Content-Type: application/json\" -d  ''{ \"leg\": 2, \"start_cur\": %s, \"start_amount\": %s ,\"dest_cur\": %s,\"best_dest_amount\": %s,\"symbol\": %s,\"deal-uuid\": %s}'' http://localhost:8080/order/', \r\n                          \r\n  deal_data -> 'cur2',\r\n  deal_data -> 'leg2-recover-amount',\r\n  deal_data -> 'cur1',\r\n  deal_data -> 'leg2-recover-target',\r\n  deal_data -> 'symbol1',\r\n  deal_data -> 'deal-uuid'\r\n  \r\n  \r\n  )\r\nFROM deal_reports\r\n where deal_uuid= '${deal_uuid}' and status in ('OK', 'InRecovery')  limit 1 ) as \"leg2\", \r\n \r\n (SELECT\r\n  format(' curl -i -X PUT -H \"Content-Type: application/json\" -d  ''{ \"leg\": 3, \"start_cur\": %s, \"start_amount\": %s ,\"dest_cur\": %s,\"best_dest_amount\": %s,\"symbol\": %s,\"deal-uuid\": %s}'' http://localhost:8080/order/', \r\n                          \r\n  deal_data -> 'cur3',\r\n  deal_data -> 'leg3-recover-amount',\r\n  deal_data -> 'cur1',\r\n  deal_data -> 'leg3-recover-target',\r\n  deal_data -> 'symbol3',\r\n  deal_data -> 'deal-uuid'\r\n  \r\n  \r\n  )\r\nFROM deal_reports\r\n where deal_uuid= '${deal_uuid}' and status in ('OK', 'InRecovery')  limit 1 ) as \"leg3\"\r\n \r\n \r\n ;\r\n"
    }
   ]
  }
 ]
}